# Server Port
server:
  port: 8082

# DataBase Configuration
spring:
  datasource:
    url: jdbc:h2:mem:product
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  h2:
    console:
    enabled: true